converter/urls.py
from django.urls import path

from . import views


app_name = 'converter'
urlpatterns = [
  # Home page
  path('', views.index, name='index'),

  # Page that shows inputs
  path('input/', views.input, name='input'),

  # Detail page for result.
  path('result/', views.result, name='result'),
]

currency_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('converter.urls')),
]

converter/models.py
from django.db import models

# Create your models here.

converter/forms.py
from django import forms

# from .models import

class UserInputForm(forms.Form):
    currency1= forms.CharField(max_length= 250,label="Enter the currency you want to convert")
    currency2 = forms.CharField(max_length=250, label="Enter the currency you want to convert to")
    value= forms.FloatField( label="Enter the Value")

converter/views.py
from django.shortcuts import render, redirect

from .forms import UserInputForm

import requests

def index(request):
  return render(request, "index.html")

def input(request):
    form = UserInputForm()
    context = {'form': form}
    return render(request, 'input.html', context)


class Currency_convertor: 
    # empty dict to store the conversion rates 
    rates = {}  
    def __init__(self, url): 
        data = requests.get(url).json() 
  
        # Extracting only the rates from the json data 
        self.rates = data["rates"]  
  
    # function to do a simple cross multiplication between  
    # the amount and the conversion rates 
    def convert(self, from_currency, to_currency, amount): 
        initial_amount = amount 
        if from_currency != 'EUR' : 
            amount = amount / self.rates[from_currency] 
  
        # limiting the precision to 2 decimal places 
        amount = round(amount * self.rates[to_currency], 2) 
        result = ('{} {} = {} {}'.format(initial_amount, from_currency, amount, to_currency))
        return result

def result(request):
  
  if request.method == 'POST': 
    form = UserInputForm(request.POST)
    
    if form.is_valid():
        currency1 = form.cleaned_data.get("currency1")
        currency2 = form.cleaned_data.get("currency2")
        value = form.cleaned_data.get("value")
        url = str.__add__('http://data.fixer.io/api/latest?access_key=', '5e6a6c2576bc2070e83a6426e6d812e4')    
        c = Currency_convertor(url)
        output = c.convert(currency1.upper(), currency2.upper(), value)
        context = {'output': output} 
        return render(request, 'result.html', context)

converter/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home Page</title>

  <style>

    .h{
      text-align: center;
    }

  </style>
</head>
<body>
  <h1 class="h">Welcome</h1>

  <button><a href="{% url 'converter:input' %}">Proceed to convert</a> </button>
</body>
</html>

converter/templates/input.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <title>Inputs</title>
</head>
<body>

  <form action="{% url 'converter:result' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Convert">

  </form>
</body>
</html>

converter/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Results</title>
</head>
<body>

  <h1>Welcome</h1>

  {{ output }}
</body>
</html>